name 'cnapp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures cnapp'
long_description 'Installs/Configures cnapp'
issues_url 'http://example.com'
source_url 'http://example.com'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)

depends 'httpd'
depends 'tomcat'
depends 'java'
depends 'haproxy'
